2020/04/22 00:11:53 ERROR: logErrorDetails:2 executionId: 6, itemResponse: &{Index:pg-2020-04-22 Type:pglog Id:gTw6n3EBMbSJE6mLCu2C Version:0 Status:400 Result: ForcedRefresh:false Found:false Error:0xc00148fcc0 GetResult:<nil>}
2020/04/22 00:11:53 ERROR: logErrorDetails:3 executionId: 6, itemResponse.Error: &{Type:illegal_argument_exception Reason:Document contains at least one immense term in field="unique_string.raw" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[115, 101, 108, 101, 99, 116, 32, 34, 117, 115, 101, 114, 115, 34, 46, 42, 32, 102, 114, 111, 109, 32, 34, 117, 115, 101, 114, 115, 34, 32]...', original message: bytes can be at most 32766 in length; got 100395 ResourceType: ResourceId: Index: Phase: Grouped:false CausedBy:map[reason:max_bytes_length_exceeded_exception: bytes can be at most 32766 in length; got 100395 type:max_bytes_length_exceeded_exception] RootCause:[] FailedShards:[]}

2020/04/22 00:12:43 ERROR: logErrorDetails:2 executionId: 7, itemResponse: &{Index:pg-2020-04-22 Type:pglog Id:Jco6n3EBvATc0BzczjBU Version:0 Status:400 Result: ForcedRefresh:false Found:false Error:0xc000a20fa0 GetResult:<nil>}
2020/04/22 00:12:43 ERROR: logErrorDetails:3 executionId: 7, itemResponse.Error: &{Type:illegal_argument_exception Reason:Document contains at least one immense term in field="unique_string.raw" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[115, 101, 108, 101, 99, 116, 32, 34, 117, 115, 101, 114, 115, 34, 46, 42, 32, 102, 114, 111, 109, 32, 34, 117, 115, 101, 114, 115, 34, 32]...', original message: bytes can be at most 32766 in length; got 100395 ResourceType: ResourceId: Index: Phase: Grouped:false CausedBy:map[reason:max_bytes_length_exceeded_exception: bytes can be at most 32766 in length; got 100395 type:max_bytes_length_exceeded_exception] RootCause:[] FailedShards:[]}

2020/04/22 00:12:53 ERROR: logErrorDetails:2 executionId: 8, itemResponse: &{Index:pg-2020-04-22 Type:pglog Id:Etc6n3EBMAV2o-i39Brp Version:0 Status:400 Result: ForcedRefresh:false Found:false Error:0xc000ea60a0 GetResult:<nil>}
2020/04/22 00:12:53 ERROR: logErrorDetails:3 executionId: 8, itemResponse.Error: &{Type:illegal_argument_exception Reason:Document contains at least one immense term in field="unique_string.raw" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[115, 101, 108, 101, 99, 116, 32, 34, 117, 115, 101, 114, 115, 34, 46, 42, 32, 102, 114, 111, 109, 32, 34, 117, 115, 101, 114, 115, 34, 32]...', original message: bytes can be at most 32766 in length; got 59041 ResourceType: ResourceId: Index: Phase: Grouped:false CausedBy:map[reason:max_bytes_length_exceeded_exception: bytes can be at most 32766 in length; got 59041 type:max_bytes_length_exceeded_exception] RootCause:[] FailedShards:[]}
